# Generated by Django 5.0.2 on 2024-02-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_analysis_datamonitored_user_delete_datamonitoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='u12', max_length=255),
        ),
    ]
