# Generated by Django 5.0.2 on 2024-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamonitored',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datamonitored',
            name='start_date',
            field=models.DateField(),
        ),
    ]
