# Generated by Django 5.0.2 on 2024-02-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_datamonitored_last_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamonitored',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.user'),
        ),
    ]
