# Generated by Django 5.0.2 on 2024-02-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_datamonitored_user_alter_monitoring_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamonitored',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
