# Generated by Django 5.0.2 on 2024-02-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_datamonitored_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='u12', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='ui', max_length=50),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='monitoring.user'),
        ),
    ]
